FROM mcr.microsoft.com/vscode/devcontainers/base:debian-10

# [Opzionale] Deselezionare questa sezione per installare pacchetti aggiuntivi.
# ESEGUIRE apt-get update && export DEBIAN_FRONTEND=noninteractive \
# && apt-get -y install --no-install-recommends <il vostro elenco di pacchetti-qui>.

